routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\PasswordController;
use App\Http\Controllers\Admin\StoreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {     return view('welcome'); })->middleware(['auth.shopify'])->name('home');

Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

Route::get('/test',function(){
dd('hii');
});
Auth::routes();

Route::get('/admin/login', [LoginController::class, 'showLoginForm'])->middleware('guest')->name('admin.login');
Route::post('/admin/login-post', [LoginController::class, 'login'])->name('admin.login.post');
Route::get('/admin/logout', [LoginController::class, 'logout'])->name('admin.logout');

Route::middleware('admin')->namespace('Admin')->prefix('admin')->group( function() {

    Route::resource('stores','\App\Http\Controllers\Admin\StoreController',['except'=>['show','update']]);
    Route::post('stores/update',[StoreController::class,'updateData'])->name('stores.update');

    Route::get('/password/change',[PasswordController::class, 'changed'])->name('password.changed');
                
    Route::post('password/post_changed', [PasswordController::class, 'postchanged'])->name('password.post.changed'); 
});
            

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;

    protected $table = 'stores';
    protected $primaryKey = 'store_id';

    protected $fillable = ['store_name','employee_name','email','mobile_no','address','state','city','pincode','status'];

    public $timestamps = true;
}

app/Http/Controllers/Admin/StoreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\StoreRequest;
use App\Models\Store;
use App\Models\Admin;
use Hash;

class StoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $type_id = auth('admin')->user()->type_id;
        if($request->ajax()){

            $where_str    = "1 = ?";
            $where_params = array(1);
            $status_type = $request->get('type');

            if (!empty($request->input('sSearch')))
            {
                $search     = $request->input('sSearch');
                $where_str .= " and (store_code like \"%{$search}%\""
                . " or store_name like \"%{$search}%\""
                . " or email like \"%{$search}%\""
                . " or mobile_no like \"%{$search}%\""
                . ")";
            }   

            if($status_type == 'inactive')
            {
                $status = 0;
                $where_str.= " and (status =$status)";
            }
            elseif($status_type == 'active')
            {
                $status = 1;
                $where_str.= " and (status =$status)";
            }
                                         

            $columns = ['store_id','store_code','store_name','email','mobile_no','status'];
            
/*            if (!empty($request->input('sony_center_wise')))
            {
                $sony_center_wise=$request->input('sony_center_wise');
                $where_str .= " And (sony_center_name ='$sony_center_wise')";
            }*/

            if($type_id == 0 ){

                $store_count = Store::select($columns)
                 ->whereRaw($where_str, $where_params)->count();

                 $store_list = Store::select($columns)
                 ->whereRaw($where_str, $where_params);

                
            }else{

                $store_count = Store::select($columns)
                ->where('store_code',$type_id)
                ->whereRaw($where_str, $where_params)->count();

                $store_list = Store::select($columns)
                ->where('store_code',$type_id)
                ->whereRaw($where_str, $where_params);

            }

            if($request->get('iDisplayStart') != '' && $request->get('iDisplayLength') != ''){
                $store_list = $store_list->take($request->input('iDisplayLength'))
                ->skip($request->input('iDisplayStart'));
            }
                    
            if($request->input('iSortCol_0')){
                $sql_order='';
                for ( $i = 0; $i < $request->input('iSortingCols'); $i++ )
                {
                    $column = $columns[$request->input('iSortCol_' . $i)];
                    if(false !== ($index = strpos($column, ' as '))){
                        $column = substr($column, 0, $index);
                    }
                    $store_list = $store_list->orderBy($column,$request->input('sSortDir_'.$i));   
                }
            }
          
            $store_list = $store_list->get();
            $response['iTotalDisplayRecords'] = $store_count;
            $response['iTotalRecords'] = $store_count;
            $response['sEcho'] = intval($request->input('sEcho'));
            $response['aaData'] = $store_list->toArray();

            

            return $response;
        }
       
        // $filter_sony_center =[""=>"Select Sony center"]+QuaterlyTcsReportData::select('sony_center_name')->distinct()->pluck('sony_center_name','sony_center_name')->toArray();
        // $path = Storage::path('public').'/tcs/';

        return view('admin.store.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('admin.store.add');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        //
        
        $store_details = new Store();
	$store_details->store_code = $request->store_code;
        $store_details->store_name = $request->store_name;
        $store_details->employee_name = $request->employee_name;
        $store_details->email = $request->email;
        $store_details->mobile_no = $request->mobile_no;
        $store_details->address = $request->address;
        $store_details->state = $request->state;
        $store_details->city = $request->city;
        $store_details->pincode = $request->pincode;
        $store_details->save();
        $store_id = $store_details->store_id;

        $admin_details = new Admin();
        $admin_details->type_id = $store_id;
        $admin_details->name = $request->employee_name;
        $admin_details->email = $request->email;
        $admin_details->mobile = $request->mobile_no;
        $admin_details->password = Hash::make($request->password);
        $admin_details->save();

        return redirect()->route('stores.index')->with('success','Store create successfully.')->with('message_type','success');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $store_data = Store::where('store_id',$id)->first();
        return view('admin.store.edit',compact('store_data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function add() {

        
    }

    public function updateData(Request $request) {

        $store_id = $request->store_id;
        $store_details = Store::find($store_id);
	$store_details->store_code = $request->store_code;
        $store_details->store_name = $request->store_name;
        $store_details->email = $request->email;
        $store_details->employee_name = $request->employee_name;
        $store_details->mobile_no = $request->mobile_no;
        $store_details->address = $request->address;
        $store_details->state = $request->state;
        $store_details->city = $request->city;
        $store_details->pincode = $request->pincode;
        $store_details->status = $request->status;
        $store_details->save();

        return redirect()->route('stores.index')->with('success','Store Update successfully.')->with('message_type','success');
        
    }
}

resources/views/admin/store/add.blade.php
@extends('admin.layout.layout')

@section('header')
    <nav class="navbar navbar-expand-xl navbar-light fixed-top hk-navbar">
        <a id="navbar_toggle_btn" class="navbar-toggle-btn nav-link-hover" href="javascript:void(0);"><span class="feather-icon"><i data-feather="menu"></i></span></a>
        <div class="hk-pg-header col-md-6">
            <h4 class="hk-pg-title"><span class="pg-title-icon"><span class="feather-icon"></span></span>Create Store</h4>
        </div>
        
    </nav>
@include('admin.layout.overlay')
@stop
@section('content')
   <div class="container">
    <div class="row">
        <div class="col-xl-12">
            <section class="hk-sec-wrapper">
                <h5 class="hk-sec-title">Create Store</h5>
                <hr>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm">
                            <form method="POST" action="https://sms.duroflexworld.com/duroflex/public/admin/stores" >
                                @csrf
                            <div class="form-group row">
                                <label class="col-xl-3" for="name">Store Code<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                   <input type="text" name="store_code" placeholder="Enter Store Code" class="form-control">
                                    <span id="order_number_error" class="help-inline text-danger">{{ $errors->first('store_code') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Store Coco<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="store_name" placeholder="Enter Store Coco" class="form-control" value="{{old('store_name')}}">
                                    <span id="reason_error" class="help-inline text-danger">{{ $errors->first('store_name') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Employee Name<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="employee_name" placeholder="Enter Employee Name" class="form-control" value="{{old('employee_name')}}">
                                    <span id="reason_error" class="help-inline text-danger">{{ $errors->first('employee_name') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Email Id<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="email" class="form-control" placeholder="Enter Email Id" value="{{old('email')}}">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('email') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Mobile Number<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="mobile_no" class="form-control" placeholder="Enter Mobile Number" value="{{old('mobile_no')}}">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('mobile_no') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Password<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="password" name="password" class="form-control" placeholder="Enter Password">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('password') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Address<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <textarea name="address" class="form-control" placeholder="Enter Address">{{old('address')}}</textarea>
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('address') }}</span>
                                </div>
                            </div>
<!--                             <div class="form-group row">
                                <label class="col-xl-3" for="description">Country<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="address" class="form-control" placeholder="Enter Country">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('country') }}</span>
                                </div>
                            </div> -->
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">State<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="state" class="form-control" placeholder="Enter State" value="{{old('state')}}">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('state') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">City<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="city" class="form-control" placeholder="Enter City" value="{{old('city')}}">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('city') }}</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3" for="description">Pincode<sup class="text-danger">*</sup></label>
                                <div class="col-sm-6">
                                    <input type="text" name="pincode" class="form-control" placeholder="Enter Pincode" value="{{old('pincode')}}">
                                    <span id="comment_error" class="help-inline text-danger">{{ $errors->first('pincode') }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="float-right">
                
                <input type="submit"  class="btn btn-sm btn-primary mr-10" value="Add Store">
             </form>   
            </div>
            <br>
            </section>
            
            
        </div>
    </div>
</div> 
@stop

@section('script')
@stop
@include('admin.layout.alert')

resources/views/admin/store/index.blade.php
@extends('admin.layout.layout')
@section('style')
{{ Html::style('backend/css/select2.min.css',[],IS_SECURE) }}
@stop
@section('header')
<form id="filter" action="" method="">
    <input type="hidden" name="type_name" value="{{Request::get('type')}}">
    {{ csrf_field()}}
    <nav class="navbar navbar-expand-xl navbar-light fixed-top hk-navbar">
        <a id="navbar_toggle_btn" class="navbar-toggle-btn nav-link-hover" href="javascript:void(0);"><span
                class="feather-icon"><i data-feather="menu"></i></span></a>
        <div class="container">
            <div class="hk-pg-header col-md-6">
                <h4 class="hk-pg-title"><span class="pg-title-icon"><span
                            class="feather-icon"></span></span>Store-Master</h4>
            </div>
            <div class="text-align-right col-md-6">

            </div>
        </div>
    </nav>
</form>
@stop
@section('content')
<div class="container">
    <div class="row">
        <div class="col-xl-12">
            <ul class="nav nav-tabs">
                <li class="@if(Request::get('type') == 'all') active @endif">
                    <a href="{{route('stores.index',['id'=>Request::get('id'),'type'=>'all'])}}">All <span
                            class="badge bg-success total_pincode"></span></a>
                </li>
                <li class="@if(Request::get('type') == 'active') active @endif">
                    <a href="{{route('stores.index',['id'=>Request::get('id'),'type'=>'active'])}}">Active <span
                            class="badge bg-success total_active_pincode"></span></a>
                </li>
                <li class="@if(Request::get('type') == 'inactive') active @endif">
                    <a href="{{route('stores.index',['id'=>Request::get('id'),'type'=>'inactive'])}}">Inactive <span
                            class="badge bg-warning total_inactive_pincode"></span></a>
                </li>
              <a href="<?= route('stores.create') ?>" class="btn btn-primary btn-sm mr-2 buttonOverAnimation" title="Add Store" style="margin-left: 700px;">
            <div data-text="Add Store" > <i class="fas fa-plus"></i>Create Store</div></a>
            </ul>
            <section class="hk-sec-wrapper">
                <div class="row">
                    <div class="col-sm">
                        <div class="table-wrap">
                            <table id="master_table" class="table table-hover w-100 display pb-30">
                                <thead>
                                    <tr>
                                        <th class="tdcheckbox"></th>
                                        <th class="tdstorecode">Store Code</th>
                                        <th class="tdcustomer">Store Coco</th>
                                        <th class="tdsonycenter">Email</th>
                                        <th class="tdsonycenter">Mobile No</th>
                                        <th class="tdstatus">Status</th>
                                        <th class="tdaction">Action</th>
                                        
                                        
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<!-- displaying import modal-->

@stop

@section('script')
{{  Html::script('backend/js/jquery.form.min.js', [],IS_SECURE) }}
{{  Html::script('backend/js/moment.min.js', [],IS_SECURE) }}
{{  Html::script('backend/js/daterangepicker.js', [],IS_SECURE) }}
{{  Html::script('backend/js/jquery.dataTables.min.js',[],IS_SECURE)  }}
{{  Html::script('backend/js/dataTables.bootstrap4.min.js',[],IS_SECURE)  }}
{{  Html::script('backend/js/dataTables.dataTables.min.js',[],IS_SECURE)  }}
{{  Html::script('backend/js/fnstandrow.js', [],IS_SECURE) }}
{{  Html::script('backend/js/nprogress.js',[],IS_SECURE)  }}
{{  Html::script('backend/js/handlebars-v4.0.12.js',[],IS_SECURE)  }}

<!-- AJAX FOR DATA TABLE  START-->

<script type="text/javascript">



    var status_type = "{{ Request::get('type') }}";
    if (status_type == 'inactive') {
        
        var url = "{{ URL::route('stores.index',['report_id'=>Request::get('id'),'type'=>'inactive'])}}";
        var url = "https://sms.duroflexworld.com/duroflex/public/admin/stores?type=inactive";
    }
    else if (status_type == 'active') {
        var url = "{{URL::route('stores.index',['report_id'=>Request::get('id'),'type'=>'active'])}}";
        var url = "https://sms.duroflexworld.com/duroflex/public/admin/stores?type=active";

    }
    else {
        var url = "{{URL::route('stores.index',['report_id'=>Request::get('id'),'type'=>'all'])}}";
	var url = "https://sms.duroflexworld.com/duroflex/public/admin/stores?type=all";

    }

    console.log(url);


        $(function(){ 
        var store_tbl = $('#master_table').dataTable({
        "bProcessing": false,
        "bServerSide": true,
        "autoWidth": true,
        "aaSorting": [
            [0, "desc"]
        ],
        lengthMenu: [
            [50, 100, 200, 500],
            ['50', '100', '200', '500']
        ],

        "sAjaxSource": url,
        "aoColumns": [
            { "mData": "store_id", bSortable: true, bVisible: false },
            {"mData":"store_code",bSortable:true, "className":"tdstorecode"},            
            { "mData": "store_name", "className": "tdcustomer", bSortable: true },
            { "mData": "email", "className": "tdcustomer", bSortable: true },
            { "mData": "mobile_no", "className": "tdcustomer", bSortable: true },

            {
                "mData": "status", "className": "tdstatus", bSortable: false,
                mRender: function (v, t, o) {
                    if (v == 1) {
                        return '<span class="badge badge-success">Active</span>';
                    } else {
                        return '<span class="badge badge-danger">Inactive</span>';
                    }
                }
            },

            {
                "mData": "store_id",
                bSortable: false,
                "className": "tdactions",
                sClass: "text-center",
                mRender: function (v, t, o) {
                var store_id = o['store_id'];
                
                var edit_urls = "stores/"+store_id+"/edit";
                var edit_url = "https://sms.duroflexworld.com/duroflex/public/admin/stores/"+store_id+"/edit";
		
                var act_html = "<div class='btn-group'>"
                    + "<a href=" + edit_url + " title='Edit Store' data-tool-tips='Edit Store' class='btn btn-xs btn-default' style='font-size:15px; line-height:9px;'><i class='glyphicon glyphicon-edit' style='color:#6f7a7f;'></i></a>"
                    + "</div>"
                return act_html;
            }
        },
            

            
        ],
    });
});

</script>
<script>
    
  @if(Session::has('error'))
  toastr.options =
  {
    "closeButton" : true,
    "progressBar" : true
  }
        toastr.error("{{ session('error') }}");
  @endif

  @if(Session::has('success'))
  toastr.options =
  {
    "closeButton" : true,
    "progressBar" : true
  }
        toastr.success("{{ session('success') }}");
  @endif

</script>

@stop